language: bash
sudo: false

addons:
  apt:
    #sources:
    #  - debian-sid
    packages:
      - libxml2-utils
      - xsltproc
      - docbook
      - docbook-xml
      - docbook-xsl
      - docbook-defguide
      - docbook-dsssl
      - w3-recs
      - opensp
      - shellcheck
script:
  - ./ci/build.sh
notifications:
  email: false
